baseURL = "http://dev.imfsoftware.com/"
languageCode = "en-us"
title = "IMF Software Solutions"

ignoreLogs = ['warning-goldmark-raw-html']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    #path = "github.com/JugglerX/hugo-hero-theme"
    path = "github.com/zerostaticthemes/hugo-hero-theme"
    disable = false
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/company-icon-32.png"
    mobile_height = "32px"
    mobile_width = "32px"
    desktop = "images/company-icon.png"
    desktop_height = "92px"
    desktop_width = "92px"
    alt = "IMF Software Solutions"

  [params.homepage_meta_tags]
    meta_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_og_title = "Hugo Hero Theme"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Hero is a multipurpose Hugo theme with fullscreen hero images and page sections. It contains content types for a business or portfolio site."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:contentbasename/"
